### ISSUE TITLE
Cyton 1500 description

### ISSUE THREAD

**Issue by SteveMacenski** [bandi13/cyton_gamma_300_ROS#2]
Hi,

I have found a fix to your issue where urdf does not work in gazebo. You do not have the proper required fields for gazebo populated. If you add mass and inertial properties to each link to the urdf, it works. I have it working in gazebo. 

use 

> roslaunch moveit_config_folder robot.launch

 to test.

**Comment by bandi13** [comment]
Hi Steve,

Do you want to send me a pull request and I'll merge it in with my version?

Thanks,
-Andras

**Comment by SteveMacenski** [comment]
It is still a work in progress and at the moment I'm only using the description node and the rest I'm working on separately. When I have something more polished, I will submit a pull request with your code and an updated urdf file with necessary gazebo launch files to work. 
One of the additions I had to add to the urdf to work in gazebo was adding in transmissions (gear reductions at the joints, if existing) and joint limits. Are these dealt with for you in the cyton_controller.yaml file? I'm unclear on what the motor init, min, max are. 

I haven't run your code yet and I was reading through it and I'm curious if your program has a simulated visual as you are commanding things with the real robot. The method I am currently using (urdf-->moveit-->controllers) by the documentation I'm reading from O'Reilly's book uses rviz for motion planning via move_group.launch file, and it executes the planned motions in gazebo from a created launch file that just opens an empty world with the urdf robot. 
Where do your movement visuals execute (or just on the hardware) since your motion planning is in rviz? Having both in not-gazebo would be awesome, but haven't been able to determine how to do that- though if you're mostly using it with real hardware, you would rarely need to have some state-simulated robot. The understanding I have is  that by adding in the information to the urdf and controllers to work in gazebo would allow you to directly communicate with the robot, but you've obviously done that quite well without it.

edited: additional clarity

**Comment by SteveMacenski** [comment]
Update: I have listed a pull request in the cyton_gamma_1500_description master on:
https://github.com/GertKanter/cyton_gamma_1500_description

see pull request for more details.
